sudo: required
services:
  - docker

before_install:
  - docker build -t gamelogist/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gamelogist/docker-react npm run test -- --coverage